# trunk-int.s.emarsys.com
class emarsys_sensitive::suite::staging::trunk_int_s_emarsys_com {

  $params = {
    'SUITE_APP_CONTACT_CONSTRING'                            => 'oViMe://DPRxZdPAq:MyGpmCEY@hzPrSLyCZjAA-ePb.HLs.FaRsydY.BxU/JJUxjz_QtwH_PqWg',
    'SUITE_APP_DEPLOY_CONSTRING'                             => '',
    'SUITE_APP_JOB_CONSTRING'                                => 'iXgBd://AFBzxUjaB:ddVXQFzz@eeXWSJcwllDm-JCl.NLs.hnXvlND.xLF/mBfIHv_ojVY_eTGk',
    'SUITE_APP_LOCAL_CONSTRING'                              => 'hvmxB://dWIYOjRGj:URiPZAyH@RNcJiDrIGXAY-xsS.jEb.OZcJDcS.yop/hxuVRa_zKRb_GEJl',
    'SUITE_APP_CONSTRING'                                    => 'DztlE://cSRDoUZOE:gOudnAzm@ASjQfQzpddgv-xdS.Jzl.pCgzKBy.NUI/jyFFWq_QVNp_ispP',
    'SUITE_APP_REPLICA_CONSTRING'                            => 'cJhBt://fWjbGqrVD:VFodpmJk@sDNvddaOJben-Che.NUS.GDeSBdl.MRf/WZPxrw_oVeO_pMVj',
    'SUITE_APP_ENVIRONMENTS_CONSTRINGS'                      => '"JMrtf-QPp.L.fLnqEJh.yXz VwuKc://FurcxIoKt:kBCbNujo@XwfdJgPgTvRq-WFh.OoB.oxjyOZh.Zsa/JfyDgE_Mypf_ZqFQ"',
    'SUITE_APP_ADMIN_CONSTRING'                              => 'cEDTl://RiIKpfryn:HYGzOICg@PCVzmICQLuKn-vvv.pLs.qoccQRL.Bsu/KLFzP_xLC_GOCxw',
    'SUITE_APP_INTEGRATIONS_CONSTRING'                       => 'KGmGU://rbQueFYiP:mihqEyHv@cSkmeUDyIXZi-ovZ.gyA.HXCZXMn.ukI/zTgFfYMwiOjS',
    'SUITE_APP_INTEGRATIONS_REPLICA_CONSTRING'               => 'yrSHS://vxScKEXUT:EVloc3Gx@yJceEdJgcOAU-zfO.sDA.DyCHhUA.YPC/dgSGfWQUXmQB',
    'SUITE_APP_MS_CONSTRING'                                 => 'EFCrY://QebqalNQz:eJdKcgrcTilLYqGziJDdVRAU@bUfzF-xblv-PDW.pDtZevS.Ou/HwTF_rBDodGo_oTcvQ_syZ',
    'SUITE_APP_BOUNCE_CONSTRING'                             => 'YQBVq://KRmxWEeIS:UljVIENH@TyBxLbWnxgdZ-hdr.YAS.ghzAcEA.HVd/Vmtpkb_Zada_UTjN',
    'SUITE_APP_AC_CONSTRING'                                 => 'eIsGU://IaxaiQivh:OoTgjadg@wMBzmSPqcmTr-HaZ.uaF.sOQSBfu.BvD/LolwhlFmEc_keoWfh',
    'SUITE_APP_MAILBOX_XPRESS_CONSTRING'                     => 'fgYeS://eOmdDJbX:mraXQXLiOPGTUgYFBbcU@Tf.cKT.YtY.kD/qPsxZL',
    'SUITE_APP_MAILBOX_POSTFIX_CONSTRING'                    => 'eClEl://XGtjnPea:iBc3uqpiifgbZqudUZzw@Ck.MAf.fMM.N8/yPyyYYX',
    'SUITE_CROSS_LOGIN_CONSTRING'                            => '',
    'SUITE_APP_AUTHENTICATION_GOOGLE2FA_FINGERPRINT_SECRET'  => 'TZmgOpIFSHCZxZRvz1u9pIoVdUnzhOFRpmGmctQczGE/nx/rCYbFIFr/QjYGmmWexy7+qXruvWnfp/sy+KBCaY==',
    'SUITE_APP_TWOFA_ENCRYPTION_KEY'                         => '+fvXtGcJtrbdiFXBdPRVhSyPYy//CVpBoumWTUiRGUlcBHYJKjeMFPSZWjNAgcPmyXDuSjNybJKqioODQPi/DZ==',
    'SUITE_APP_AC_API_SECRET'                                => 'BQrmufduPLDelGNo6LLeK5nrVCEZKbQz',
    'SUITE_APP_AC_ACCESS_KEY_ID'                             => 'qwTR3DVAUijFshAqqhyo2aZwlamAHcGy',
    'SUITE_APP_AC_REPORTING_RABBITMQ_URL'                    => 'LZQw://KwVBFvkAy-EmPUpVApa:EuKefpfPKuGNnahlHnht@npOgD-zi-hibYWqbV-GRH:3Zd7/WdPRTYljX',
    'SUITE_APP_TREND_REPORTING_SECRET'                       => 'EqFwinbA',
    'SUITE_APP_TREND_REPORTING_ESCHER_SECRET'                => 'dEgOdViuOQFPslpIxJjpTHobZcIJiGFW',
    'SUITE_APP_NOTIFICATION_CENTER_AUTH_TOKEN'               => 'h1LmifDvUOuQyODOSEkKKfkBb4xWijUeKJIJY5siGRd3NF',
    'SUITE_APP_NOTIFICATION_CENTER_AUTH_SECRET'              => 'DqALooImxss9Pyw4RNegCFSWOmleZvsS5zImPXYgkk0qzO',
    'SUITE_APP_API_AUTH_ENCRYPTION_KEY'                      => 'XbvUSDZFfbkYMbyZPOtelzSOpsgXatdXDidteppiaS+oJZoeiTJLEhioITPZyixewFGhElVk+Le/DBqQGOMqfm==',
    'SUITE_APP_ESCHER_KEYPOOL_ENCRYPTION_KEY'                => 'ixfnx8bnDJVtemIntmWHtdrkWJgulbJjjW+g/lOHkXOGlObLbCUMptkyigcezYAyfpzQPrkH5wGGdmgacKmkiV==',
    'SUITE_APP_ESCHER_KEYPOOL_ENCRYPTION_KEYS'               => '"[x5_GslR7QcVbCKkzOktVvFjkNzlRMObPpaqbS+g/vvfMTBvUrnWSdIXVeqlmIdtFwbxkwNxvZstK1CYITQgeGgJNx==]"',
    'SUITE_APP_SALESFORCE_ACCOUNT_INFO_ACCESS_TOKEN'         => 'oeFicRZkxOQlnXvmUVbqqJpBNl1=',
    'SUITE_APP_CAMPAIGN_SENDINGTIME_LINKTRACKER_SIGNING_KEY' => 'ygZiYZIHoOTjwbCx1vILeDAxOwYNXPRo4Hu4WASRkAO=',
    'SUITE_APP_ZENDESK_API_TOKEN'                            => 'dXnMiFqBRhphVNzGPcegDvIGISHMqhSQvneUmbDg',
    'SUITE_APP_NEXMO_API_KEY'                                => 'Ff5rDvjX',
    'SUITE_APP_NEXMO_API_SECRET'                             => 'bgjufQLK',
    'SUITE_APP_KEYRING_MASTER_PASSPHRASE'                    => 'fNx)kFEsCZWKtSNWUcfFLL)ZpajIHHdv',
    'SUITE_APP_SMS_LOGIN_PASSWORD'                           => 'zBUSFkAC',
    'SUITE_APP_XMLRPC_PASSWORD'                              => 'CumYpdN7oB',
    'SUITE_HIPCHAT_ROOM_SUITENOTIFICATIONS_AUTHTOKEN'        => 'JshmkOrJNryvDMPjeC7sZAdaTWECIVPhJCveFnoI',
    'SUITE_HIPCHAT_ROOM_ITOOLS_ALERTS_AUTHTOKEN'             => 'opZscdrgVhLLYtVkmRsGivYpXssVuArNQxMCEELD',
    'SUITE_HIPCHAT_ROOM_3RDPLATFORM_AUTHTOKEN'               => 'UeQnGbWiIwDngQSNGvYWzbqSEyaAMZfrsmUbvpYf',
    'SUITE_HIPCHAT_ROOM_DEPLOYMENT_AUTHTOKEN'                => 'JcCfpxGhfzekMUQbCDv8qqfKDLTZUPEhwZyPelYX',
    'SUITE_HIPCHAT_ROOM_TCS_AUTHTOKEN'                       => 'OIvTvfc7OlPCyJNEZIuDfUaCdKsOlRlvTNvguanN',
    'SUITE_HIPCHAT_ROOM_LOFASZTEST_AUTHTOKEN'                => 'tdsSSVhKb5amRtfzWfXTONhgWXiMrLLyXTyPeEfz',
    'SUITE_APP_PERCONA_CONSTRING'                            => 'gaGPv://ZveBAiLpdivrUZJ:PMtKhUQehIACAhQJjAmdGAtbnFqEQMam@lBiLOOpmfszQ-FOm.JEC.ZEHCMMt.IjI/bjgaGA_jKYv_rAhd',
    'SUITE_APP_DER_KOMMANDER_SECRET'                         => 'GRMQjoOVxqUkDEFAsPIaLUqNvoXK2ItH',
    'SUITE_APP_CODE_PROFILER_JWT_SECRET'                     => 'toMzFZujZjlPiRyB',
    'SUITE_APP_CEPH_KEY'                                     => 'rUpZKZXwlnNPnTUpZuPx',
    'SUITE_APP_CEPH_SECRET'                                  => 'YXQbjtWNyqfvPgWVAiRo6alkVVhFRBywcpoKmycV',
    'SUITE_APP_TCM_QUEUE_PASSWORD'                           => 'nsOsiASuZu',
    'SUITE_APP_DATAPLATFORM_CLICK_QUEUE_PASSWORD'            => 'UqqhptCUFbAPAnUKFnNx',
    'SUITE_APP_SEEDLIST_API_BASEURL'                         => 'iTxbD://VTsedEJck6wq2yQs2SIvoUbzITDyOx9iyioGVlQi@zlx.UJQsElcmmd.uoi/zW/',
    'SUITE_APP_TABLEAU_CONSTRING'                            => '"XfUS=lk.Oy5.YHf.uMT XXle=bwcI MKEdIv=YfFemDaKk zrEp=CnqzZVw rvdlwgGn=nFuGiNI"',
    'SUITE_APP_DWH_CONSTRING'                                => '"pkuk=Fy.GlB.cv1.oO oVxk=XmK5 bFLlIv=pWtGXzo uDIL=sdlmWkb lotvBCJI=XbRPsCV"',
    'SUITE_APP_JIRA_USERNAME'                                => 'aWJEObwDa',
    'SUITE_APP_JIRA_PASSWORD'                                => 'xNnuMrJTIwGGnL',
    'SUITE_APP_EMSADMIN_INACTIVE_CUSTOMER_PASSWORD'          => 'VVLAxubU',
    'SUITE_APP_OMNITURE_USERNAME'                            => 'vZGFOTp_tciwSdey',
    'SUITE_APP_OMNITURE_PASSWORD'                            => 'unIDd1up*O*g',
    'SUITE_APP_OMNITURE_PRODUCT_CODE'                        => '4wYh6foJUwnlWcuC',
    'SUITE_APP_OMNITURE_INTEGRATION_CODE'                    => 'k5dePglKlp1fCOmS',
    'SUITE_APP_RTM_REPORTS_USERNAME'                         => 'SlNGYRvtKn_DtmWlHLGtHshoNtG',
    'SUITE_APP_RTM_REPORTS_PASSWORD'                         => 'WOvMGInEXGATJMBZZzTa',
    'SUITE_APP_SALESFORCE_USERNAME'                          => 'BHhOP@cAAsrGK.BXo',
    'SUITE_APP_SALESFORCE_PASSWORD'                          => 'RiMOPRYbcQDd',
    'SUITE_APP_SALESFORCE_TOKEN'                             => 'spSWVUwxTHucVW3kOvWnKIdn',
    'SUITE_APP_SALESFORCE_SANDBOX_USERNAME'                  => 'HvAvl@UrZHQNo.Tzf.WqRyaVv',
    'SUITE_APP_SALESFORCE_SANDBOX_PASSWORD'                  => 'fOqoTzGSTvyW',
    'SUITE_APP_SALESFORCE_SANDBOX_TOKEN'                     => 'VFqUBrabUySNsEWqNqNeerAe',
    'SUITE_APP_LITMUS_USERNAME'                              => 'NqhjGHA-Flf',
    'SUITE_APP_LITMUS_PASSWORD'                              => 'gETadKZrlFEK',
    'SUITE_APP_SALES_FORCE_USERNAME'                         => 'ClzJr.uFCZINn@LGiTkFy.xJb',
    'SUITE_APP_SALES_FORCE_TOKEN'                            => 'DB2tjMcC-FEbI-9FUP-qLi9-PZ2UD81irDId',
    'SUITE_APP_KPI_TOKEN'                                    => 'fLDJNsuzpfQwqZaCxoPH',
    'SUITE_APP_PROWL_API_KEYS'                               => '"[EfH9XupZviUftQ7a4qIcSLXQQxtXSAiwDPyArVLT, SjjtgAuPREtdeDDZkjQhmb58FAIbrusBA8khQ3KF]"',
    'SUITE_HIPCHAT_ROOM_OPS_ALERTS_AUTHTOKEN'                => 'qHqtNmzDVVkMnsLKELsTbeHWGcKjdkGPMxNmdYFV',
    'SUITE_APP_VERSION_VIEWER_TOKEN'                         => 'vuWYmSajLwoVXjZxzXZYzHWjijBApt8K',
    'SUITE_XMLRPC_SERVER_MAILBOX_DEFAULT_PWD'                => 'GHGLaNScYpn',
    'SUITE_APP_GPG_PASSPHRASE'                               => 'wuWnm3Yi',
    'RO_VIP_CONSTRING'                                       => 'uEJuc://ISKCPiJRj:udrozFjm@RWxRkNVPtrOM-RGp-bo.saY.IbAWcJu.kXy/aSHCjQ_khmF_EjMy',
    'RW_VIP_CONSTRING'                                       => 'XAhJE://fQdkzgoug:otoAwfd1@nVElMSoJtxKz-Lia.MWT.BqPEEhz.UsS/aJjoqB_PHbj_kvZR',
    'OPS_VIP_CONSTRING'                                      => 'EooDT://PlvNnndQS:WqXmU3MG@aAsJCXsEKcqh-FIA.Ngf.IKOZcEe.nBI/tFvrZR_iUwh_oWUi',
    'DESIGNRO_VIP_CONSTRING'                                 => 'PafMr://aOxwocih:DZRtNLcviyRGzTLWUioUNzGn@QPTAPCxmAPbQ-RYK-Og.Iud.XKkCece.Eul/upeXkE_OdfN_jBk6',
    'SUITE_APP_GEO_QUEUE_PASSWORD'                           => 'siNOcTBnh6',
    'SUITE_APP_BEHAVIOUR_QUEUE_PASSWORD'                     => 'mbdAPphSYT',
    'SUITE_APP_PUBSUB_EVENT_QUEUE_PASS'                      => '"drtPwDSRWaHXqjgOwrYj"',
    'SUITE_APP_PERSONALIZATION_CONSTRING'                    => 'mAcRY://IsoikJSaZr:GkmxmjRppAgHammerjHS@hjqBuKWsVKoe-qCV.lcN.pGMRoOx.ZEJ/ZRqbkD_jpZO_vvx3',
    'SUITE_APP_CONTACT_CHANGE_QUEUE_PASSWORD'                => 'PytlOckENuRYLywmP5Ol',
    'SUITE_APP_WSSE_ENCRYPTION_KEYS'                         => '"[aA_GuULQKaqwTNUvwed6xsEPOmantzyEysPGlytv/mAyKqoRB0RxVwVIzxeaLwAvIw7FQoRyqK+/XklBShkuDWOPL==]"',
    'SUITE_APP_VONAGE_API_KEY'                               => 'HQvux4J6',
    'SUITE_APP_VONAGE_API_SECRET'                            => 'hCL0ZsuzIuwWxjvY',
  }

}
