# trunk-int.s.emarsys.com
class emarsys_sensitive::suite::staging::trunk_int_s_emarsys_com {

  $params = {
    'SUITE_APP_CONTACT_CONSTRING'                            => 'lgkid://nYWTHdfEF:mwBLX5nX@LsmWMmwzWfOw-ynW.xfJ.VSHcaKE.nZQ/sqdivI_lIlW_ReiF',
    'SUITE_APP_DEPLOY_CONSTRING'                             => '',
    'SUITE_APP_JOB_CONSTRING'                                => 'QLRgy://AmFApFVlp:STTosNTS@syIimGwJanSv-UHK.ydR.VrDwdiG.nGt/ubvumt_UKOa_AUtK',
    'SUITE_APP_LOCAL_CONSTRING'                              => 'HjCiG://dNTxSDYdR:TIrrCoWX@ezsqtUAfqCls-TZa.DbN.ITjGsmv.nAj/AoBlJg_IqTP_taqr',
    'SUITE_APP_CONSTRING'                                    => 'FxJzN://BXeyeQdWK:oDFHICmM@fiPjtYmxvheT-QYk.vps.omueEjI.nTx/waPSeN_fCLL_wElM',
    'SUITE_APP_REPLICA_CONSTRING'                            => 'yvHPT://JnwOQzxdG:dooFKzbv@IMgfptOLYoKx-VDJ.ZcW.pKZCajC.nJD/ncYaoq_PRBO_VtFK',
    'SUITE_APP_ENVIRONMENTS_CONSTRINGS'                      => '"xWQnV-fnm.H.AUQwLNW.orW xNLXo://EBrsfvADU:URoUzOgQ@kzopNtIRqgCf-Xec.FqN.dwDKtUR.nDx/hTLhfh_LRgu_WHRV"',
    'SUITE_APP_ADMIN_CONSTRING'                              => 'CuCmw://TpyPACJpY:GzhONlUH@bLdvlYAqJwwV-KWf.PbD.bWhszpF.nuk/DlWnx_EnG_QDsXn',
    'SUITE_APP_INTEGRATIONS_CONSTRING'                       => 'shskV://dBCJLGYeC:BlwaHwZm@TXmfVOPuOMNv-iCR.FKV.kVIeYfo.nid/dnWmWOekspnj',
    'SUITE_APP_INTEGRATIONS_REPLICA_CONSTRING'               => 'lnylJ://mOoolNYbs:OQGqIRRC@WXcXWTJyocRf-dEl.PVp.GcsDGzJ.nrb/WnrYfJeaUDnQ',
    'SUITE_APP_MS_CONSTRING'                                 => 'aPqCS://BjPYWFdTb:bZGnJKagZhmVhIXukzvylnaH@rEmhs-mUjO-ChM.ebQXvpf.BF/FwsQ_GdnsonW_WKynZ_XnX',
    'SUITE_APP_BOUNCE_CONSTRING'                             => 'tHYuP://KgZPLUxZo:ohUBXPYp@zrlhlkTkwBWS-Kmy.MCC.qqkoRIS.nfp/AuMcBW_QKyW_mHC0',
    'SUITE_APP_AC_CONSTRING'                                 => 'wUgAo://nhNXOuqqP:cKlmadgF@MkmgfdzeWPlo-fEI.dtP.OPpDWkk.nPH/USuLNDLFDn_ICnJKT',
    'SUITE_APP_MAILBOX_XPRESS_CONSTRING'                     => 'czjmo://wDLVvQpn:JDnrKVwTwDXWfpitnbLT@6H.vgj.lCV.sT/daIeda',
    'SUITE_APP_MAILBOX_POSTFIX_CONSTRING'                    => 'WJnqM://uLBQKXrn:wHnxFNsxExeZbjLVnpUl@X9.HUk.Ct8.Z4/tuRIXKN',
    'SUITE_CROSS_LOGIN_CONSTRING'                            => '',
    'SUITE_APP_AUTHENTICATION_GOOGLE2FA_FINGERPRINT_SECRET'  => 'hdyRPjHURIUkfMjtrXJeUFLQTnMRYWCus0dayUvbqNC/iw/yXgnvCtL/lYtKJrIblO7+llACGFmFu/tI+WVrie==',
    'SUITE_APP_TWOFA_ENCRYPTION_KEY'                         => '+nFgg9iPSXuGO1KRvnnHIhfKIu//lWVj5UQULEZJbHnurGJ0IcOgKdXrAqiqWXGIcjuvxdpIlNVKUtkhWqX/LA==',
    'SUITE_APP_AC_API_SECRET'                                => 'WekkJS7nvBhrUrmssYsS9cMnCXkbmGye',
    'SUITE_APP_AC_ACCESS_KEY_ID'                             => 'GIFU4m78kPLOV1MOVwBhut2GNHem2gjW',
    'SUITE_APP_AC_REPORTING_RABBITMQ_URL'                    => 'EOGT://LXdIzGmny-TUcVqpqYT:haiStCXHkHjqLYmwgkqY@mKHbe-Kr-NZUlAiNS-UCn:13Rh/ErhOjohnS',
    'SUITE_APP_TREND_REPORTING_SECRET'                       => 'OaHeAwIL',
    'SUITE_APP_TREND_REPORTING_ESCHER_SECRET'                => 'QsVJknnZ3yRWUnjcYhUPisxmwFrUUJTG',
    'SUITE_APP_NOTIFICATION_CENTER_AUTH_TOKEN'               => 'KRYRdTnug8KZPg7EblnFAkkCMm3fAUiqjJayXniCfJHvlk',
    'SUITE_APP_NOTIFICATION_CENTER_AUTH_SECRET'              => 'wOOpv11x8ZoxP0kJ0Q5MgbU6O4mJMeGhV0yvAyZCchjhTT',
    'SUITE_APP_API_AUTH_ENCRYPTION_KEY'                      => 'YMRNvrLJOjaESVNKXsUGYmBlwCstBNqhxKOZgAKSRM+PmaiNfNuuBnJNtJwvSTRtu5mGkWio+RO/zxAQBSfm5H==',
    'SUITE_APP_ESCHER_KEYPOOL_ENCRYPTION_KEY'                => 'TRoGQFXenvdITxoytYWceyttLPOBUREdmJ+h/MTrZkIfqipYHhaoYkWtujyvXyTDLohAKltQawxFbGLSissjUX==',
    'SUITE_APP_ESCHER_KEYPOOL_ENCRYPTION_KEYS'               => '"[sH_tKdWmvcunWQ3GkoNXmaIcUjHVxNfYQbjMY+t/yLcdHvVABKwXzMnLMNbcxIdXjzwcoBtlnYH1IrdieWDgIJTzH==]"',
    'SUITE_APP_SALESFORCE_ACCOUNT_INFO_ACCESS_TOKEN'         => 'mkgzbFqtSdeuY7nUGZcJqrWnm1I=',
    'SUITE_APP_CAMPAIGN_SENDINGTIME_LINKTRACKER_SIGNING_KEY' => 'XcsFJEuGCngEYlrtbcOq2zjPHDZhUAFTOKtFymioSGJ=',
    'SUITE_APP_ZENDESK_API_TOKEN'                            => 'gFVqQFvjPAMrzyBVZjHpkpAxElxCk4FUobmaKnRP',
    'SUITE_APP_NEXMO_API_KEY'                                => 'fv4dZxnb',
    'SUITE_APP_NEXMO_API_SECRET'                             => 'IwS4M3ha',
    'SUITE_APP_KEYRING_MASTER_PASSPHRASE'                    => 'cGr)JmbZJNIJQFqwDrWXAI)nntSRBHzs',
    'SUITE_APP_SMS_LOGIN_PASSWORD'                           => 'RDQWnMoH',
    'SUITE_APP_XMLRPC_PASSWORD'                              => 'XwPSfR463D',
    'SUITE_HIPCHAT_ROOM_SUITENOTIFICATIONS_AUTHTOKEN'        => 'mjQXrSRJiHfdpvaXBnyzkUGXMiBAUqFEnXviAErg',
    'SUITE_HIPCHAT_ROOM_ITOOLS_ALERTS_AUTHTOKEN'             => 'xfExbAWYiDHGxxDgeCPIihcBTVrGpZyvlRFZGAjM',
    'SUITE_HIPCHAT_ROOM_3RDPLATFORM_AUTHTOKEN'               => '5czkDkaEkYBkQLnySztTdaygBvkHzYnXnNUQxvcD',
    'SUITE_HIPCHAT_ROOM_DEPLOYMENT_AUTHTOKEN'                => '1WrcdPazGJTqIZfYxdcxmlxZGhTNlfMljmfGfcUV',
    'SUITE_HIPCHAT_ROOM_TCS_AUTHTOKEN'                       => 'HeBkVpihbtqaEQlGiLfqnHrYbAlosZrPpwaJLqNu',
    'SUITE_HIPCHAT_ROOM_LOFASZTEST_AUTHTOKEN'                => 'phkTqtrIJkceqvbqBhphDTmnAIKZoncdvbrLBxwF',
    'SUITE_APP_PERCONA_CONSTRING'                            => 'RsxCn://qgZnbsngpBCnipO:oqMcLfjsIXa5njg5pNlKhRnu5ocPUWcE@fPypsVFTZnGi-OPn.vPz.EuPMkwY.nQf/ULzmAX_fazz_GemJ',
    'SUITE_APP_DER_KOMMANDER_SECRET'                         => 'QlrLgMplRIzMoXjYidTiHUWrpGWokUXN',
    'SUITE_APP_CODE_PROFILER_JWT_SECRET'                     => 'nf2jHuoOYomDDgTL',
    'SUITE_APP_CEPH_KEY'                                     => 'rYrlwgDDehAGah5ImgOe',
    'SUITE_APP_CEPH_SECRET'                                  => 'JIjjibroRjmiZQenvJNFVLMGKmdtYqZoAeMKSGWW',
    'SUITE_APP_TCM_QUEUE_PASSWORD'                           => 'OnrpnQrozw',
    'SUITE_APP_DATAPLATFORM_CLICK_QUEUE_PASSWORD'            => 'yKDnbAlUlkdaK0MTvKxd',
    'SUITE_APP_SEEDLIST_API_BASEURL'                         => 'sBwqf://hkm1DqUDXW9y2DfONIeugMJTabIP3cVBMcls8euQ@tMr.mQoqpnvSEN.qyc/L9/',
    'SUITE_APP_TABLEAU_CONSTRING'                            => '"RYrm=12.trJ.kBD.o79 FtMs=p28C NbnZCL=MEappNuUx jNXU=RXwFwmX dKlGzURM=TnfAoml"',
    'SUITE_APP_DWH_CONSTRING'                                => '"JWpy=QX.2Vi.PiB.U6 XeBa=pyo6 mJnWKi=eIhuezD oDcx=cGhbZRN BZOpCBzR=anASchU"',
    'SUITE_APP_JIRA_USERNAME'                                => 'ozRLJpbCV',
    'SUITE_APP_JIRA_PASSWORD'                                => 'eSNAqsSdzHPY0W',
    'SUITE_APP_EMSADMIN_INACTIVE_CUSTOMER_PASSWORD'          => 'zJgvEOZt',
    'SUITE_APP_OMNITURE_USERNAME'                            => 'PgIyrvf_ziWnHRhy',
    'SUITE_APP_OMNITURE_PASSWORD'                            => 'lDXySGNi*k*m',
    'SUITE_APP_OMNITURE_PRODUCT_CODE'                        => 'm1DRV5dIoKfKlDap',
    'SUITE_APP_OMNITURE_INTEGRATION_CODE'                    => 'PLl1LCQfcdTfezfk',
    'SUITE_APP_RTM_REPORTS_USERNAME'                         => 'IKVJtxnnfm_ZQrnxNrCWSniobWt',
    'SUITE_APP_RTM_REPORTS_PASSWORD'                         => 'jkSnUBUeBmhIyvInlYQI',
    'SUITE_APP_SALESFORCE_USERNAME'                          => 'xOGvQ@uzIKwat.RrM',
    'SUITE_APP_SALESFORCE_PASSWORD'                          => 'hPiYAsOnvon3',
    'SUITE_APP_SALESFORCE_TOKEN'                             => 'cmBJQeHXFAbBYyoRDdJeeMkk',
    'SUITE_APP_SALESFORCE_SANDBOX_USERNAME'                  => 'nkIeC@NIYcZfu.LMX.zRrPyzo',
    'SUITE_APP_SALESFORCE_SANDBOX_PASSWORD'                  => 'mZkyZvKnt894',
    'SUITE_APP_SALESFORCE_SANDBOX_TOKEN'                     => 'khtbaTkVknaLQTknpNRYlbDM',
    'SUITE_APP_LITMUS_USERNAME'                              => 'zjlhhvD-ABF',
    'SUITE_APP_LITMUS_PASSWORD'                              => 'GCZcudnxNUMW',
    'SUITE_APP_SALES_FORCE_USERNAME'                         => 'FOoMn.LwnnBjA@HEQlqbP.QTR',
    'SUITE_APP_SALES_FORCE_TOKEN'                            => 'gZTnOzNs-gZwM-ZCYB-qDPv-qI2a2MlTO99x',
    'SUITE_APP_KPI_TOKEN'                                    => 'KczyejnLnDThDPShZLly',
    'SUITE_APP_PROWL_API_KEYS'                               => '"[zKwoDtEb8WbBCIhf2kefhhSvUBPD9Q4hu9VlnfaZ, sgvm0k7RmnbHdMtFtoWJE1Q01QbEcxx1kNoAUk9H]"',
    'SUITE_HIPCHAT_ROOM_OPS_ALERTS_AUTHTOKEN'                => 'JjoDD3pNrTujpDcGLdcbuXugntnIWbavdjkMIaBO',
    'SUITE_APP_VERSION_VIEWER_TOKEN'                         => 'ua772RmTXOphEQhWfxyXBBHPrcY6NJqo',
    'SUITE_XMLRPC_SERVER_MAILBOX_DEFAULT_PWD'                => 'WyZoDSLruF1',
    'SUITE_APP_GPG_PASSPHRASE'                               => 'ereHn5oM',
    'RO_VIP_CONSTRING'                                       => 'pfJUN://bFspNYCVG:YorzHhim@KLhtPxLmpQDi-ftK-Hw.aQJ.nPiOZNj.ntp/AemKRY_Kfnu_jGKP',
    'RW_VIP_CONSTRING'                                       => 'nZphv://sesdRyHkQ:XqnwdRka@FmNNcISvlmXh-OpA.Dik.XFmlPMI.npq/DZKELB_WSot_MzNc',
    'OPS_VIP_CONSTRING'                                      => 'JkgUD://weixHtOve:gSZyyXUU@NtHvTLpUHlLP-dEi.zMy.BIaIbLr.nag/Iphjbh_ylAr_jOla',
    'DESIGNRO_VIP_CONSTRING'                                 => 'rcXrj://VQRLznzg:2rBodpzSyJUftnhZNnCdrwfa@vIcjikPgMSru-zmf-Jw.cas.bPcoklq.nHD/tQFeDB_mtYy_rADW',
    'SUITE_APP_GEO_QUEUE_PASSWORD'                           => 'IngznlzrUm',
    'SUITE_APP_BEHAVIOUR_QUEUE_PASSWORD'                     => 'kngfnjWsJY',
    'SUITE_APP_PUBSUB_EVENT_QUEUE_PASS'                      => '"MBbIeotBFWIqVXoyFVIr"',
    'SUITE_APP_PERSONALIZATION_CONSTRING'                    => 'RrbpC://gOXQdyjrpm:UUTfrEdtV3dUkvaCJ4oT@JabdmYjEwKyF-MGg.eLp.IvzrGfl.nkT/IvTrpp_XZTR_idtX',
    'SUITE_APP_CONTACT_CHANGE_QUEUE_PASSWORD'                => 'KRDDkWwAYMophIu9vHQe',
    'SUITE_APP_WSSE_ENCRYPTION_KEYS'                         => '"[ZO_dAoASNxnkLmKUKqK0COK9BWtYqBRLkPEZBdPA/goTBjHQLELyYYWhUuxYBXcmEo2kUTgUnJ+/HNqe6cKTJUNJw==]"',
    'SUITE_APP_VONAGE_API_KEY'                               => 'mMOUM8iQ',
    'SUITE_APP_VONAGE_API_SECRET'                            => 'nYACBIyWXoNZIqUA',
  }

}
